#ifndef	_GENERIC_TIMER_H
#define	_GENERIC_TIMER_H

#define CORE0_TIMER_IRQCNTL 0x40000040
#define CORE1_TIMER_IRQCNTL 0x40000044 
#define CORE2_TIMER_IRQCNTL 0x40000048 
#define CORE3_TIMER_IRQCNTL 0x4000004C 

#define TIMER_IRQCNTL_CNTVIRQ_FIQ_ENABLED   (1 << 7)
#define TIMER_IRQCNTL_CNTHPIRQ_FIQ_ENABLED  (1 << 6)
#define TIMER_IRQCNTL_CNTPNSIRQ_FIQ_ENABLED (1 << 5)
#define TIMER_IRQCNTL_CNTPSIRQ_FIQ_ENABLED  (1 << 4)
#define TIMER_IRQCNTL_CNTVIRQ_IRQ_ENABLED   (1 << 3)
#define TIMER_IRQCNTL_CNTHPIRQ_IRQ_ENABLED  (1 << 2)
#define TIMER_IRQCNTL_CNTPNSIRQ_IRQ_ENABLED (1 << 1)
#define TIMER_IRQCNTL_CNTPSIRQ_IRQ_ENABLED  (1 << 0)

void timer_init ( void );
void handle_timer_irq ( void );

#endif  /*_GENERIC_TIMER_H */
