#ifndef _P_GPIO_REGS_H
#define _P_GPIO_REGS_H

#include "boards/raspi3/raspi3.h"

#define GPFSEL0_OFFSET      (0x00)
#define GPFSEL1_OFFSET      (0x04)
#define GPFSEL2_OFFSET      (0x08)
#define GPFSEL3_OFFSET      (0x0C)
#define GPFSEL4_OFFSET      (0x10)
#define GPFSEL5_OFFSET      (0x14)
#define GPSET0_OFFSET       (0x1C)
#define GPSET1_OFFSET       (0x20)
#define GPCLR0_OFFSET       (0x28)
#define GPLEV0_OFFSET       (0x34)
#define GPLEV1_OFFSET       (0x38)
#define GPEDS0_OFFSET       (0x40)
#define GPEDS1_OFFSET       (0x44)
#define GPHEN0_OFFSET       (0x64)
#define GPHEN1_OFFSET       (0x68)
#define GPPUD_OFFSET        (0x94)
#define GPPUDCLK0_OFFSET    (0x98)
#define GPPUDCLK1_OFFSET    (0x9C)

#define GPIO_BASE           (PA_DEVICE_BASE + 0x00200000)
#define GPFSEL0             (GPIO_BASE + GPFSEL0_OFFSET)
#define GPFSEL1             (GPIO_BASE + GPFSEL1_OFFSET)
#define GPFSEL2             (GPIO_BASE + GPFSEL2_OFFSET)
#define GPFSEL3             (GPIO_BASE + GPFSEL3_OFFSET)
#define GPFSEL4             (GPIO_BASE + GPFSEL4_OFFSET)
#define GPFSEL5             (GPIO_BASE + GPFSEL5_OFFSET)
#define GPSET0              (GPIO_BASE + GPSET0_OFFSET)
#define GPSET1              (GPIO_BASE + GPSET1_OFFSET)
#define GPCLR0              (GPIO_BASE + GPCLR0_OFFSET)
#define GPLEV0              (GPIO_BASE + GPLEV0_OFFSET)
#define GPLEV1              (GPIO_BASE + GPLEV1_OFFSET)
#define GPEDS0              (GPIO_BASE + GPEDS0_OFFSET)
#define GPEDS1              (GPIO_BASE + GPEDS1_OFFSET)
#define GPHEN0              (GPIO_BASE + GPHEN0_OFFSET)
#define GPHEN1              (GPIO_BASE + GPHEN1_OFFSET)
#define GPPUD               (GPIO_BASE + GPPUD_OFFSET)
#define GPPUDCLK0           (GPIO_BASE + GPPUDCLK0_OFFSET)
#define GPPUDCLK1           (GPIO_BASE + GPPUDCLK1_OFFSET)

#endif  /*_P_GPIO_REGS_H */
