#ifndef	_P_MINI_UART_REGS_H
#define	_P_MINI_UART_REGS_H

#include "peripherals/base.h"

#define AUX_ENABLES_OFFSET     (0x04)
#define AUX_MU_IO_REG_OFFSET   (0x40)
#define AUX_MU_IER_REG_OFFSET  (0x44)
#define AUX_MU_IIR_REG_OFFSET  (0x48)
#define AUX_MU_LCR_REG_OFFSET  (0x4C)
#define AUX_MU_MCR_REG_OFFSET  (0x50)
#define AUX_MU_LSR_REG_OFFSET  (0x54)
#define AUX_MU_MSR_REG_OFFSET  (0x58)
#define AUX_MU_SCRATCH_OFFSET  (0x5C)
#define AUX_MU_CNTL_REG_OFFSET (0x60)
#define AUX_MU_STAT_REG_OFFSET (0x64)
#define AUX_MU_BAUD_REG_OFFSET (0x68)

#define AUX_BASE                (PBASE + 0x00215000)
#define AUX_ENABLES             (AUX_BASE + AUX_ENABLES_OFFSET)
#define AUX_MU_IO_REG           (AUX_BASE + AUX_MU_IO_REG_OFFSET)
#define AUX_MU_IER_REG          (AUX_BASE + AUX_MU_IER_REG_OFFSET)
#define AUX_MU_IIR_REG          (AUX_BASE + AUX_MU_IIR_REG_OFFSET)
#define AUX_MU_LCR_REG          (AUX_BASE + AUX_MU_LCR_REG_OFFSET)
#define AUX_MU_MCR_REG          (AUX_BASE + AUX_MU_MCR_REG_OFFSET)
#define AUX_MU_LSR_REG          (AUX_BASE + AUX_MU_LSR_REG_OFFSET)
#define AUX_MU_MSR_REG          (AUX_BASE + AUX_MU_MSR_REG_OFFSET)
#define AUX_MU_SCRATCH          (AUX_BASE + AUX_MU_SCRATCH_OFFSET)
#define AUX_MU_CNTL_REG         (AUX_BASE + AUX_MU_CNTL_REG_OFFSET)
#define AUX_MU_STAT_REG         (AUX_BASE + AUX_MU_STAT_REG_OFFSET)
#define AUX_MU_BAUD_REG         (AUX_BASE + AUX_MU_BAUD_REG_OFFSET)

#endif  /*_P_MINI_UART_REGS_H */
